#!/bin/bash
sudo apt update
sudo apt install -y  software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible
sudo git clone https://github.com/Far00qM/ansible-nginx.git
sudo ansible-playbook --connection=local --inventory 127.0.0.1, ansible-nginx/ansible-nginx.yml

